namespace: postiz-application

# Required secrets for Postiz
JWT_SECRET: "# REQUIRED: Set a secure JWT secret (e.g., base64:...)"
DATABASE_URL: "# REQUIRED: Set PostgreSQL connection URL (e.g., postgresql://user:pass@host:5432/dbname)"
REDIS_URL: "redis://postiz-application-redis-master:6379"

# PostgreSQL passwords for database setup
postgresql-postgres-password: "# REQUIRED: Set a secure PostgreSQL admin password"
postgresql-password: "# REQUIRED: Set a secure PostgreSQL user password"

# Redis password
redis-password: "# REQUIRED: Set a secure Redis password"

# Social Media API Keys (optional - leave empty if not used)
X_API_KEY: ""
X_API_SECRET: ""
LINKEDIN_CLIENT_ID: ""
LINKEDIN_CLIENT_SECRET: ""
REDDIT_CLIENT_ID: ""
REDDIT_CLIENT_SECRET: ""
GITHUB_CLIENT_ID: ""
GITHUB_CLIENT_SECRET: ""

# OpenAI API Key (optional - leave empty if not used)
OPENAI_API_KEY: ""