apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-url: {{ (index .Values "db-url" | default "" | toString | b64enc) | quote }}
  db-name: {{ (index .Values "db-name" | default "" | toString | b64enc) | quote }}
  db-user: {{ (index .Values "db-user" | default "" | toString | b64enc) | quote }}
  db-password: {{ (index .Values "db-password" | default "" | toString | b64enc) | quote }}
  redis-password: {{ (index .Values "redis-password" | default "" | toString | b64enc) | quote }}
  jwt-secret: {{ (index .Values "jwt-secret" | default "" | toString | b64enc) | quote }}
  email-from-address: {{ (index .Values "email-from-address" | default "" | toString | b64enc) | quote }}
  email-from-name: {{ (index .Values "email-from-name" | default "" | toString | b64enc) | quote }}
  cloudflare-account-id: {{ (index .Values "cloudflare-account-id" | default "" | toString | b64enc) | quote }}
  cloudflare-access-key: {{ (index .Values "cloudflare-access-key" | default "" | toString | b64enc) | quote }}
  cloudflare-secret-access-key: {{ (index .Values "cloudflare-secret-access-key" | default "" | toString | b64enc) | quote }}
  cloudflare-bucketname: {{ (index .Values "cloudflare-bucketname" | default "" | toString | b64enc) | quote }}
  cloudflare-bucket-url: {{ (index .Values "cloudflare-bucket-url" | default "" | toString | b64enc) | quote }}
  cloudflare-region: {{ (index .Values "cloudflare-region" | default "" | toString | b64enc) | quote }}
  discord-client-id: {{ (index .Values "discord-client-id" | default "" | toString | b64enc) | quote }}
  discord-client-secret: {{ (index .Values "discord-client-secret" | default "" | toString | b64enc) | quote }}
  discord-bot-token-id: {{ (index .Values "discord-bot-token-id" | default "" | toString | b64enc) | quote }}
  github-client-id: {{ (index .Values "github-client-id" | default "" | toString | b64enc) | quote }}
  github-client-secret: {{ (index .Values "github-client-secret" | default "" | toString | b64enc) | quote }}
  telegram-bot-token: {{ (index .Values "telegram-bot-token" | default "" | toString | b64enc) | quote }}
  telegram-bot-name: {{ (index .Values "telegram-bot-name" | default "" | toString | b64enc) | quote }}
  threads-client-id: {{ (index .Values "threads-client-id" | default "" | toString | b64enc) | quote }}
  threads-client-secret: {{ (index .Values "threads-client-secret" | default "" | toString | b64enc) | quote }}
  facebook-app-id: {{ (index .Values "facebook-app-id" | default "" | toString | b64enc) | quote }}
  facebook-app-secret: {{ (index .Values "facebook-app-secret" | default "" | toString | b64enc) | quote }}
  linkedin-client-id: {{ (index .Values "linkedin-client-id" | default "" | toString | b64enc) | quote }}
  linkedin-client-secret: {{ (index .Values "linkedin-client-secret" | default "" | toString | b64enc) | quote }}
  pinterest-client-id: {{ (index .Values "pinterest-client-id" | default "" | toString | b64enc) | quote }}
  pinterest-client-secret: {{ (index .Values "pinterest-client-secret" | default "" | toString | b64enc) | quote }}
  reddit-client-id: {{ (index .Values "reddit-client-id" | default "" | toString | b64enc) | quote }}
  reddit-client-secret: {{ (index .Values "reddit-client-secret" | default "" | toString | b64enc) | quote }}
  slack-id: {{ (index .Values "slack-id" | default "" | toString | b64enc) | quote }}
  slack-secret: {{ (index .Values "slack-secret" | default "" | toString | b64enc) | quote }}
  slack-signing-secret: {{ (index .Values "slack-signing-secret" | default "" | toString | b64enc) | quote }}
  x-api-key: {{ (index .Values "x-api-key" | default "" | toString | b64enc) | quote }}
  x-api-secret: {{ (index .Values "x-api-secret" | default "" | toString | b64enc) | quote }}
  youtube-client-id: {{ (index .Values "youtube-client-id" | default "" | toString | b64enc) | quote }}
  youtube-client-secret: {{ (index .Values "youtube-client-secret" | default "" | toString | b64enc) | quote }}
  openai-api-key: {{ (index .Values "openai-api-key" | default "" | toString | b64enc) | quote }}
