apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: application-application-system
  namespace: organisation
  title: application-application System
  description: |
    Placeholder description
  labels:
    tier: "3"
  annotations:
    github.com/project-slug: organisation/application-application
    backstage.io/adr-location: docs/adrs
    backstage.io/techdocs-ref: dir:./docs/techdocs
    simpleicons.org/icon-slug: n8n
  tags:
    - application-application
  links:
    - url: https://application-application.organisation.test/
      title: Development URL
      icon: dashboard
      type: website
    - url: https://application-application.staging.k8s.organisation.nl/
      title: Staging URL
      icon: dashboard
      type: website
    - url: https://github.com/organisation/application-application
      title: Source Code
      icon: github
      type: source
spec:
  owner: group:organisation/infrastructure
  domain: organisation/operations-domain
  type: product
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: application-application
  namespace: organisation
  title: application
  description: |
    Placeholder description
  labels:
    tier: "3"
  annotations:
    github.com/project-slug: organisation/application-application
    backstage.io/techdocs-ref: dir:./docs/techdocs
    simpleicons.org/icon-slug: n8n
  tags:
    - application
    - nodejs
    - automation
  links:
    - url: https://application-application.organisation.test/
      title: Development URL
      icon: dashboard
      type: website
    - url: https://application-application.staging.k8s.organisation.nl/
      title: Staging URL
      icon: dashboard
      type: website
    - url: https://github.com/organisation/application-application
      title: Source Code
      icon: github
      type: source
spec:
  type: service
  lifecycle: development
  owner: group:organisation/infrastructure
  system: application-application-system
