namespace: ENC[AES256_GCM,data:2KysITFoq4mtN7X/IYTMn1xi,iv:pghdNZVRP5ym74rtTjTCOlaOl3UsT/twEEAy5ux5AZs=,tag:kCNqQaSqSglHt0qo5DX7mw==,type:str]
db-name: ENC[AES256_GCM,data:uuN/QFXo,iv:h7z83NljuXHIriUQzn170n/dh7zsX16ki5HH/SLDJCw=,tag:rTV0Qq07RwnxW41of4bWlQ==,type:str]
db-user: ENC[AES256_GCM,data:7B6cJhuU,iv:fF4jnYXdW0ypl5bYm9usptqWCVXLpbMwMILUdNJXVBI=,tag:M3+vxtnNsuY8Mme1MCPXjg==,type:str]
db-password: ENC[AES256_GCM,data:RDDbpm1Ucpu1hVg6TKsd,iv:oN4pdVTkUaWf1bJSnkZCk0mZEAUxZLfJ2OD5eFGBAH0=,tag:8gwCKBzNkf1f+/N7qcTi4Q==,type:str]
db-url: ENC[AES256_GCM,data:BGazIUC2H8bQkJanyFhV/2NpM8ltiXEUkcp2px3q0P6xVUMZYfLqV5W86aVHLDlYY+6ir/MECBaKfw6q+hA1b8kumtveEJIFFZXAZEKmVS1W6dkFvzgx4pPBU/JBPeo=,iv:ucJktlyGi8dEsqb7xEwR/5nfETaAkMN60WTzZH8xf0c=,tag:plJbjVNVUczIg8MI2UgZeA==,type:str]
redis-password: ENC[AES256_GCM,data:tROJCKPdc5Rpw+TZqDZuYQXV+qU1,iv:UWmUf9FBZWGG837BEPkvMgWVpoClzKAh23xSJFmdkMY=,tag:aaI0oHstag+1XvO2ElEGHQ==,type:str]
jwt-secret: ENC[AES256_GCM,data:PL3CwyGaMQBZWfJPoj8xRLoMQRVwzdA/tYu54VMBAFxNEQItHsFZumicezCsiaeBOT5zmB7d8dh9J+uNBwvGpubKfclUe2ZIm6bq6A==,iv:WA1S11g9k6JOj2u4n5ffyl0f9P/KiPU+9LxT3VqGbbo=,tag:0ZTdrsTuDEP1QWRHhaxE5w==,type:str]
email-from-address: ENC[AES256_GCM,data:1uThHYaX4Ms38UlZXfrXBySY,iv:18cyAEaSVdfqypwWh0QukRSjh9NuZndJoK9WtjMkeFs=,tag:z9dOdxlWO8cV18x39je8sg==,type:str]
email-from-name: ENC[AES256_GCM,data:CvKGoukgEQ==,iv:bRDf8ZUjnSQiPyHIAdi662whW+rM1TBU369AXGQIc7E=,tag:NZkZRMD/geHmREgAY4O5ng==,type:str]
cloudflare-account-id: ENC[AES256_GCM,data:6EqTcaiDf24DQTiNYCMbkTKmBhpPGFO9z1cbIl56xf4=,iv:RhWtd3rxEX63wioWidDzNy0x6nhhJ+lNBlgR4EI8sNM=,tag:tWZp9b6CKRKYlEnos1LNVw==,type:str]
cloudflare-access-key: ENC[AES256_GCM,data:LdArmrO0aWanUJR9XSFHb4L9saO4SjijGabEOS09tm0=,iv:n0EK+ZqVw1VLrrvOZ69LyyaI8MHgERMeZweQ4EWl664=,tag:XJqVPKmJKKLC7+JUrqUq9w==,type:str]
cloudflare-secret-access-key: ENC[AES256_GCM,data:ET50GuufceAsgzK4yrdlf2i9un3foJXK/WBeoCR6nPulf7Qi/ihNwug9HaJoGmkDxve5FC9o99Raz+tP3cZejQ==,iv:GQEjzcpFoqi/JfPiqK66YoXGWRd5E+TNKZrLrI+y+R8=,tag:nfx3piqMQDz8bYzpa6ocxQ==,type:str]
cloudflare-bucketname: ENC[AES256_GCM,data:zPs14kF6,iv:9AtH4gdJEF0qPcbHIj9YzzkqIb5lWNOGnp0OjJps+Ho=,tag:YVgxnZKrCwvwnOce+baQgg==,type:str]
cloudflare-bucket-url: ENC[AES256_GCM,data:TaOV4GWFzSG4xPtql8XCQbyr5/paBe/qgst3Hr7z8IKbZGbEze2TD1QUoNrBw3XcLJVVOcjzdGxtoHrrY2DM4N4=,iv:YtSFbnfJOROfkX/lIBLahjDBEogQjA9L3W3F5ZTZE8A=,tag:YPbndeSlIrvqEm8kKfHuCw==,type:str]
cloudflare-region: ENC[AES256_GCM,data:t52wqA==,iv:05WBjvN1WNZ4j1gXgvhmjXDeZvJbV9QB4lwONPAnS34=,tag:NFddsVTtebC6wy6Cj+2xAw==,type:str]
discord-client-id: ENC[AES256_GCM,data:hsXfxb/Z4Wv1rF2Id6PHPVq9Xg==,iv:zQfTDFwbpUn5bLDbxdVAPE1kJd//dZSr340tyBqfimw=,tag:wLIJ6xVzqM6maSk0fFREZQ==,type:str]
discord-client-secret: ENC[AES256_GCM,data:M6cx+jZaVpB1J5QaKhzApTUJC2BGRHdJ7OPle3nm5XY=,iv:JvMS4CIHGjixjOY/30PisFUMEaogeuWeJaF40GLAVCo=,tag:W/K+oknLuX/r4x0ZiPU0GA==,type:str]
discord-bot-token-id: ENC[AES256_GCM,data:4nEB0ZYN+CtSbF/tq7345mwX/+shwQHeru/BYd3YKnrveUPqvFun0VUjnFceAUyjyQ7iCpWfRv6JYFoGfHmCW+RAU09A30t4,iv:fVET4Ic2fmEucx/49S0uuFvNEgmSrwzGHs4UbUD/Ud0=,tag:8tjkgf+ceWwo/ydNYknm2A==,type:str]
github-client-id: ""
github-client-secret: ""
telegram-bot-token: ""
telegram-bot-name: ""
threads-client-id: ""
threads-client-secret: ""
facebook-app-id: ""
facebook-app-secret: ""
linkedin-client-id: ENC[AES256_GCM,data://kllDuU6FwOm1G9YeM=,iv:6TGGZ585pNUMpHJJXQPpbKuxH2gjnnKInpNCRPGLNtk=,tag:3q23VRCWrpXFYK6NBjnloQ==,type:str]
linkedin-client-secret: ENC[AES256_GCM,data:wleS6QDZIp4Z5h+m/vPn8wMipu4t52e7Ek6oZZGsRPtV,iv:jTz5kZPTAluDX/JArU7CQJwotnsypuvdwJ4u5fVzgWE=,tag:UkjohEzKWzxeQsQAgCyfSA==,type:str]
pinterest-client-id: ""
pinterest-client-secret: ""
reddit-client-id: ENC[AES256_GCM,data:SEWxPg/8vDMukph8EITCvfSNTFxELA==,iv:jVqCIdBCohk/oYEktbki5JljBlrgMizHDYOaIqTlh/w=,tag:6IaBQR/6Bty45m+3/1+XYA==,type:str]
reddit-client-secret: ENC[AES256_GCM,data:eE98KFHB99tchU9cVokZ6nTXUN7hcybIhfuvEhdB,iv:ooE2n4RsycSWFif8Ppf9EqVp34WLIxWB+182WIH0GGU=,tag:VoA/ELaTqFe+2HS4VHiixg==,type:str]
slack-id: ENC[AES256_GCM,data:tPSMcxrZ15Co0FNk3+eCwmezjSz1X66xGy49,iv:XoV52fmMEv66Ew9bfuCOtcs1VtdxZ8DUe4GbjNT/axc=,tag:dIT5Bdyrbd7v1NUXDrT8ow==,type:str]
slack-secret: ENC[AES256_GCM,data:/M6H8AAb7s1sBjZd5yPRLTiyrRsWwjuFUhHWoG/2a2Q=,iv:RORUG2SZBix1hVqXO5vGy0XXT5iFKCkQ4O1gEBjIVpo=,tag:SJj8A9esDmPJDxEPEzukeg==,type:str]
slack-signing-secret: ENC[AES256_GCM,data:aO5npA5GKJTATivW5IpcXW7yAHY0mHco6nOHuMBccJo=,iv:jvo2Oayj9Ci+FeITNFqi4UlzLoMRCKIUnRtcPjcHPQU=,tag:OzYTYplTT1Vd0AqdP9d0jg==,type:str]
x-api-key: ENC[AES256_GCM,data:l4Tr0CdF0l+uALi/NsvyaYETmVnHWdByVZIL6PpfMSqtlw==,iv:3B9Alvrv+UeWw5lGyNn4pSV/AGZLqsLcvnFFL2/Fnbs=,tag:GBQ06E7Bvxgy9GZDo4HzZw==,type:str]
x-api-secret: ENC[AES256_GCM,data:3lQZcRCgRSg0NsA2IKNrA8P3t8Oj1WZuVAZ6zxcz+bduFhLHZY5eOmahzreMoSwavFs=,iv:TNTw6eWWSboWGLdOq3l3Zvk4HFV/rMtJWw9/xgliFOU=,tag:dhDdEBgWhaEFNrE+248Ngw==,type:str]
youtube-client-id: ENC[AES256_GCM,data:lhkQsDX0dO1lBcc8ZI5jMbfAWmQrhh13i+HpgGl7cgXVwYAqxErU+XmbVC8GZunBgH2ijyQC1SiWytcwGPaV5Vg5bPqL8i7j,iv:cJQiyXfA2wV8w+DKirr0S9qfTQvbasIELtgVjwTGFo8=,tag:ZCQZBcz0dtR4qKMuwQLEbw==,type:str]
youtube-client-secret: ENC[AES256_GCM,data:D1F9H8wqulErQkNZdOGpVwV3nj1rsMUwDz1YDFNqlYJt+w0=,iv:IKotR6iNvFm31MhXImjrGe4byY1Y64dXPDBZw3XS5Ag=,tag:ZOeNf7UZ4URGjG5p/+fD5A==,type:str]
openai-api-key: ENC[AES256_GCM,data:cNV2wyWgWqy4/Q3KUQ0GcgI/JSG/wBdyoomWQieBkAKeiC46IU+WiEwbvuh6N4xa/b4TxpchzDFHWIMUPEyJfWvZ2MI07boMXIuFomH2viqI9XU/qeUJRBchdIa4VQfgDENv64U9GTtqcQtx6ryxiopw5a+mx4E7omL25fPD5sGQ5umYa0EtymD8PXgCrmFRIYhYEMZk5vtIsKDVXLV0aZEKiJ4=,iv:cqZ7PyXUBTTcjP+l9nd55/fgff5IJOSfGjeZJkSXgRk=,tag:/aDjuJ4szP24/3pRdYkZ9Q==,type:str]
sops:
    age:
        - recipient: age1ypmym3g6ql22en2r22czt4r98c6pqljtppv64qk0kdez2ydf5uxqqytgzs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbXJ1VXEzMm1SMXJxYVBw
            aStxL09NN1kwbTVzdjkxL2RBejB1YTJXUGtJCm1aRHZFalkxNytTVVFUQ2Nzcit2
            Tm0yRFNmRG13b3pSNytuZEo5L0RFV0EKLS0tIC9ObDcwOThvUEt4dkZKbkp4Q0o4
            Q1NmMnhzUXVDblgydC9sL2YwV2VFdUkK13IRh3KB6tR/aq/fIbIZcoS2uotntepL
            gVUrADZFpp/bHnPitAoQCzA+C3aIOuL3FRZSQ1rvxTrLh1ooAYS6bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T10:51:32Z"
    mac: ENC[AES256_GCM,data:8YO/575aD9HE+ArlTh06qGhNWM0OkmDC6OjvVVko3wjq0Yec+0tEZ1kBlSX5QLg2CxqA9q7EjCvjmaBqXD/Uzh3HSnIW4PmTvPE2U/31xwQ5li+sPsdzdh3Mb2kzbLuhnrqeLYxnC7Bg+ohzzrHV+tCF6Q1X6GCj2ffWVFA+xPo=,iv:NVGNWfKGW6jBktRwlPg2RQpw62yn86NXw6BWgUTmXCY=,tag:cD4oJjiOaBIgprtWxMWP5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
