namespace: ENC[AES256_GCM,data:FpAyYQjx23oQIk2WsN1tse1o,iv:LJJ0+y32H/9SvwsxBDZi3K/FvEjV65t4FJsdvKfmq7M=,tag:MgEKrBkNQ+V9N9lPBGd5LQ==,type:str]
db-name: ENC[AES256_GCM,data:NzO0WVh2,iv:ev7W6iO2cNI6+18yE59sJrXlDlHozYcVeYAWoaqScEM=,tag:Eu4KGzC9/HDKUaU2/3O3xg==,type:str]
db-user: ENC[AES256_GCM,data:v38tioYt,iv:jzhT4ErxbViMwLqvhqEkzKdRxdHUhqRT0R0ZBazw6fA=,tag:pOOQkgDyR1Kl8BqZp/ytSw==,type:str]
db-password: ENC[AES256_GCM,data:OMNJZRaJZg3++X7WjzDl,iv:Bcsa+bWXKPqVjq2dQrq2bRvOtJV2snRgGMh9+9NTzKQ=,tag:0ODxGQXORc73Xd296/dl4Q==,type:str]
db-url: ENC[AES256_GCM,data:jWl4D+wt0NW0cW9zglMi6aY3D+uyxgQP/vbWDxlrcaqIAvjxu1LDwnO8idYOqkae+53abNmXwbQh0qWCCPQ6Y8DvAHoGCWpFr1xc2ELkc3Qu02ShVCIO8ItgeuV70WY=,iv:l4cZyz48N1d8R0Qp1QURXI2nkJq09+yXg7X2bualAp8=,tag:v7A68eRNxPs6atCIun/xtA==,type:str]
redis-password: ENC[AES256_GCM,data:b/LqrQm692GLWn6ERBQ/rRbbh5q0,iv:j40WDtJeUMve3Pvh4wACWYMDGSs25K4zH5VOrypOpjs=,tag:z8OT0gNNqYoBCntuLh7KrQ==,type:str]
jwt-secret: ENC[AES256_GCM,data:ZoH4szMD/MRuvZM/88dviHRJrAQKv7I6YU3GzbWdMD15IL1KxWGdXeCGy8QXFXIhjC9RCzPWIoJSsNYU9nURVlkaoiQRclp3uoICwQ==,iv:BsuqYalzTCOPRbSCzhNyw96JP2qhTuiE5wvGxhZgVK0=,tag:yFeZQhjemIIKpOtHLUPs9A==,type:str]
email-from-address: ENC[AES256_GCM,data:nP1ix1YZbiBaQY7Thu2wvwFo,iv:cH5KRS7CBHYD/7q70Oa4PF9qSG5NhOOpStLrQt0+AEo=,tag:TKcqkeWyGEItl/Z56J0f+A==,type:str]
email-from-name: ENC[AES256_GCM,data:Vj5y/ad0nA==,iv:5gxoweKnh8i2R/bRxZjTMigZY506eKNqmTqGrOJ/wFY=,tag:Jy70u15jvCF/pP6ng4nCww==,type:str]
cloudflare-account-id: ENC[AES256_GCM,data:4RZqy/uilbdlKgfY3tGeAvsX106cpfIjpcNkLgngTag=,iv:51JLrT+fBKNjXRcdKWPznlb35XD8HHR8gtR366roo8g=,tag:yFuPpNfEZMBo5sP056O3rQ==,type:str]
cloudflare-access-key: ENC[AES256_GCM,data:SIpJBEExle0d+J+hx1BkdFB6TIG/+Rp/8s53h5of9+Q=,iv:rHGTmyfUnLvC1OLniC82D4x03M8+qsCJgaYY0mJTsX4=,tag:vBg1kr6clKWMq2whttaVcw==,type:str]
cloudflare-secret-access-key: ENC[AES256_GCM,data:i0tDgt39dwgwIibNFasJGhJwWaHuoiXlmWNdnURhlG2yucW8ZQf9GZvQoqyfvIKN9h/uK0UE5P1/gq4KotyndQ==,iv:vqrX7F9ehO9+SIyIr8VSAOykHQOU/AFFhWE5jsnfFhQ=,tag:vB392DR60MkhD4Scg0Wm3Q==,type:str]
cloudflare-bucketname: ENC[AES256_GCM,data:8jEdvI7c,iv:XgG4yZQg62JvXrTCnS6u5DWfC6wU/SSzlM+0ToDSpPc=,tag:hmggJ4RpEfamJKcid2F3lA==,type:str]
cloudflare-bucket-url: ENC[AES256_GCM,data:XVgba/sMLm9flagHXGcyxE1Ac0irmVxIcHlg6foNh01sPkca3wMxGk+PTeRheYwNBUP7diQXUUOGzeEP6qP2X9c=,iv:ZSjTtS0NQTGhNDtdsZuZbKcVvdkt9suOfQVWpvbCAo4=,tag:k/M31UZtt1TyyrUYzIWpaA==,type:str]
cloudflare-region: ENC[AES256_GCM,data:Qq+njg==,iv:Qyb3alHup/C+TziBk4jCtv9Efvb+tfPjf/GB4xbr/sk=,tag:Oksydk+Jf8xJpfrpwc/JrA==,type:str]
discord-client-id: ENC[AES256_GCM,data:k8fbul8SAAMcu3I1rMXfh2T/7A==,iv:0EcflhKbwlCvjgc+ET+V9YWxlL9CwjI8mBWXlPbbpTU=,tag:NV4S2vRhQpluuYM8wMiqaA==,type:str]
discord-client-secret: ENC[AES256_GCM,data:03sBJzIhq9lD+ycmxSmLjNfpL0VCpNu64opEyg0HIHs=,iv:jwPX1FrRzls6ShTx2b/yQowedjt7ETH2+3Km+wiF9fA=,tag:TihkmqAjeO+0t0nazt9kjw==,type:str]
discord-bot-token-id: ENC[AES256_GCM,data:ytqLR/xGlCngFna1EaPHuH1zsYkCHif3fDf49jqdjJtn6kxauC7gLWZvl6jTN/Hfm1kSCpidDOxOPDDqvoS4dxo3e1qu7bD5,iv:8CYLlqIyX1admo/dB9sDrkQ9EYMf83x/lKxsvCg3LDo=,tag:rkJwmv+FfWVCW4xmQSX4PA==,type:str]
github-client-id: ""
github-client-secret: ""
telegram-bot-token: ""
telegram-bot-name: ""
threads-client-id: ""
threads-client-secret: ""
facebook-app-id: ""
facebook-app-secret: ""
linkedin-client-id: ENC[AES256_GCM,data:3A1svZqr3i0GmK2OFe0=,iv:0gOvzqO1kMESrUz3k1w4i5gcnmlkDqO/wKEfIcV+Hc0=,tag:TNvqjLoeGassNZu2tuMQQw==,type:str]
linkedin-client-secret: ENC[AES256_GCM,data:xIwxW3gpLLeo0FmKE0cB/lGhBzcVEiBEhmg6chGL3kV3,iv:VsPX0UnJpMKpj0lvHTIFtqu9MI3Aqa6OOvYimhUVPw0=,tag:AnLXN/GEBx+ckJdZutH/qw==,type:str]
pinterest-client-id: ""
pinterest-client-secret: ""
reddit-client-id: ENC[AES256_GCM,data:RN1Ti85ku9/WbfvtsvXugqqB7cO+4A==,iv:L2ecR68TM9N2WVUyjc81c/F6uDYz2Slm8IciDbHl2Bg=,tag:OAeNBTvbBs4X0J+Z/i1MZg==,type:str]
reddit-client-secret: ENC[AES256_GCM,data:vCDRDoizRF3OjDU7AdrfohUhSPBvLXsbhfAVCSu9,iv:aqwDH9L6eIGquy/pHXAXtyjd85axUEufe98cxu8Ef0g=,tag:tB+mC7lbHnwpVtEGVWkGjg==,type:str]
slack-id: ENC[AES256_GCM,data:GuordRTXIudyBRdOkw/19AEMWDQ9I5tQLlym,iv:u5cO3xSr/yMcqx4Tq69KJbaNtaCMop+h4qR/t+H/LP0=,tag:EklGZMLPsMkhG5CEZ2WEgg==,type:str]
slack-secret: ENC[AES256_GCM,data:d5wh5e9m4jg7XLtJ8TOKGwCfOGm4ai4YvvKy2/trdns=,iv:RC+4XDN8ycmX9zmWp8DL2ryGJL1tqwzRSm11eu9t8KE=,tag:A3CaFymEnawJoCmBIhtukg==,type:str]
slack-signing-secret: ENC[AES256_GCM,data:odMqpXnpyFtiK+1BCxACNZdnCseQp6uHhBzDzLKsL00=,iv:X/6boxN8pkhWD1KIo2NN/Pwzx5oNpbdcwlOLC7PmEbk=,tag:ABcrLBawhXUGHXkALKThXw==,type:str]
x-api-key: ENC[AES256_GCM,data:zByNvj47uZnVY6wPeXtJVoz8IBd0smd5BrniB9D2TqRTMA==,iv:KNXrvA9GLuDRto8NLYtMpbHGmtZy27PeNZnPdkPq2IM=,tag:nCY0sIjormi453hElnqCXQ==,type:str]
x-api-secret: ENC[AES256_GCM,data:O+f1+GJhMSPUPFLpyEG6m91TLGmNgslebIMopKWSCp18FS1vIRFQxmMyhVPghpYTPaY=,iv:pBuBs+fewEAaoHQ+hgYE4+7yhRkIrAJMKpgdPNMQjEc=,tag:YUIC0O/jSaE17e2Mj3bJ3A==,type:str]
youtube-client-id: ENC[AES256_GCM,data:skumSCAC4ZDM9yHqnycLXPGr6QZeyYHB5MdXoRxh2PnwuPeZpXVCxReZLodwxPddPYMWo9gjbf8MtoFN1eKlM2uetmCmqJBZ,iv:Z924d2cZBZN+T3mwHyK4xc8iC5+87lJ//oiLyrfNXyY=,tag:GxB+CsOhdDQVwL7ZTpKFtA==,type:str]
youtube-client-secret: ENC[AES256_GCM,data:Sy7Ai+ADMCM/JojyKWPBsempyocqOwviKKlhmsJih9/K74c=,iv:szIpFx5XaS/svi5wj6df1czlnbTQvgL7uk8hO7b+WXY=,tag:66eKXicVF86d2rYp5ovpAQ==,type:str]
openai-api-key: ENC[AES256_GCM,data:zRkXEG5JEUYe52F1/UURT0gqNgwh//Tm7xAGNG6cNGx5EJdBYaWUvGD5BmuBfta7YhmFmcrhs8rd2oRKxkRE7aDQwiygnteomMu0nkrx+O41gOtpVOgRsffReyfXNusD6IqDUCVeH9Otzi5Jk8eirc6ukMbUGTYLG6DlYuCAqu9LltzpADFfpGkqaKQuP6Fn4e49rZvsGO5t4dhZOjnRfRAyL88=,iv:iDf4iQbz7rDeRgnSzXAHt3aMAUf+PfHJ5WXLrS5YxA4=,tag:N++AYVMnUqeA51e7PXuaug==,type:str]
sops:
    age:
        - recipient: age1ypmym3g6ql22en2r22czt4r98c6pqljtppv64qk0kdez2ydf5uxqqytgzs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOVZzL2daM0xhSms1bU4y
            SkYxTmREYjNONHljbTVFVkZvWEpTVzNMbEJBCjdZWlRLUVZmZWlqeHEvMForZzdH
            b0ZOVURLbFBqdTc0Q3hkdXdyTmF1ek0KLS0tIHZCUFBDaXpveU5nVUhObFJrbU1v
            OEFrVUlCU2lMSkZMRExkRTZtWkFkSE0KMqeXASBD6EzHzmD3003AYq4yEuJ3gIEh
            dzgK44SgFTplIG7uyIkxGvmkSgWSoXHYjepZ0oSUvPFp3w90DwtJew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T10:29:49Z"
    mac: ENC[AES256_GCM,data:wOf7t2gy+agm/ounEs468DanP0hnI+UNb14e4TQ6CkDrr52jsy/kXAlUFhSBOaymjLpU0t/suiVYpwIhMTnuqgOyTZ5jzSWS3Pn/ogIFnAvt3vn3c5uNoTypevvKSkVdMBTd438LWBo+SFszhk7n4rrXu9m094zcJiFKb5TSyUA=,iv:flEuz1lkPHO9hI2hkLdIbCufxrfa6+voVHU1BquEYL0=,tag:fjMdBNg/6/dlRozF4NiEeQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
