namespace: ENC[AES256_GCM,data:IigO2pg6/vSC3gr72ZRBZg9t,iv:ilW2lSgfV/KBE2tn66aalhZgNtYVCJqx4Dgk5qT860E=,tag:L1zlWsr9OEV0jand0TgVaQ==,type:str]
db-name: ENC[AES256_GCM,data:YlzBkCik,iv:pNFwyOEvuGcPrIVmoX/gSRFfL5HfMad+s0IvdvHSLm4=,tag:2Df5pTzz8z6VQ8nMFP/6Jw==,type:str]
db-user: ENC[AES256_GCM,data:gRzMTRhv,iv:4BHjtleBXR7lJWAbmbK/iih/H//wQAloZqO07qwWltY=,tag:r90Bj2MBJ+u8B0pETMVvqQ==,type:str]
db-password: ENC[AES256_GCM,data:fSaGz2EnxCqV6HfLHjGT,iv:08q/QcQSaGL6QYtV/MsZuDbjzBzEzkZxILTv+3gCdLA=,tag:bfD3zbwMBGdj5I7MIlLNmg==,type:str]
db-url: ENC[AES256_GCM,data:EdSQoxQ/pPYQpJthqZgYQPickI6z8U5pXPsw2bM21gpZ7WCLbSeh83POaTVTU5s9+Ju1zDvq+xMrVQUI4b0YJe7n0zZW5gf9YqZbxytdRyxoCsijMjgOptTYc7g9cRc=,iv:8ZR+Yxol5y9O1Lt9FomJG4NPvM7KyiFwriOeFK7mFNk=,tag:9DkUCAL+Z1v2SLAdfsr6Iw==,type:str]
redis-password: ENC[AES256_GCM,data:1qLTWJFdlZxlXF16wkn0biuApOKl,iv:uHKWQbkU47W0M6wIlBtLER5fnUGtBcYpg0HWv5nWMXs=,tag:AYs6yghURuwRYaGW0kAP9w==,type:str]
jwt-secret: ENC[AES256_GCM,data:nr27Bj10iDh9Gnk3zEdUi5E3l+6I6dPmMVkHVjiHBtg3BRQy9ChxR0tEu4uhBhINeh18oEtg9aEMH3ywc4ioE7tbr5pVQX+M1DZdjQ==,iv:pnVJAthQ5ZxtkqC7fl0QiNJLRiz3Msvk7VFI6T4PYmg=,tag:rHzxyHsENK4qZ/aSO4Emdg==,type:str]
email-from-address: ENC[AES256_GCM,data:N8X0wKMwCKZ7kqidrD+BxpSI,iv:Riv0Wq+FvJgTBb7YaCqSlG1TOLWbF3FbDesSct/nJYI=,tag:NKK3MQqLfpMMx/xpL4IiZA==,type:str]
email-from-name: ENC[AES256_GCM,data:EASApiWBcA==,iv:TfpNJQxN6YMPZxoQf901wNjUg5c4JJku8U4uVSoBvj4=,tag:YOXDznYDpGZNpMGrWXuQ7Q==,type:str]
cloudflare-account-id: ENC[AES256_GCM,data:BBfEO07jYEQHP73r2tb879hBtpwuTNygJ3LuwiQ4nEE=,iv:/e0LXMf4TQpEywFPl3FN1Peajda9AFnU5I3LL1E32lE=,tag:oyH+ko4bu+E9OEWsZUuOcg==,type:str]
cloudflare-access-key: ENC[AES256_GCM,data:2oPEctAVyuwMAxnnwWGs0jiER1ok+QujpZ5ImN4CKt4=,iv:CqCRb0CTSTZn11SgddOz9Tky0iesKZlMRlAIYNjT5o8=,tag:QDla9lREK8WcganGE5amfw==,type:str]
cloudflare-secret-access-key: ENC[AES256_GCM,data:5gIuLJBPoMDJc5vCZUo6XDHicaWZ2HEfuYlNzt3/WainmTBv8cGxF0shjidLkq2gwZvDZT5l4+IF85DKvCOe6A==,iv:vDFKbLrzk+PEb31ulbz27SOdy3sE+Z/YzgCexy7PYz8=,tag:NGjfmXnPQjikTD/hV74PxQ==,type:str]
cloudflare-bucketname: ENC[AES256_GCM,data:h6d+eZ4s,iv:YyAAkHSrxKgPS7Fjkx9KPgCk3qWMnvdBnc/aI5CSicc=,tag:AgmaPQjtEqzWg/ohipUP+g==,type:str]
cloudflare-bucket-url: ENC[AES256_GCM,data:R81T8suDk9fBxwBn8mdMN+aOnGQtORUipnOMJvVARES8iyYvJ3/D9StDdrBo8e3eJtc/2JOY45hWeGZntomr9ls=,iv:qaI5fIngJVSWRwkbifY5gzgjITRzGbPHAR2huMogfto=,tag:9744j7nkrJPZTVKUlNF/xQ==,type:str]
cloudflare-region: ENC[AES256_GCM,data:+Av+Qw==,iv:hHyiPUHrPnXLlfB+jHIy8p0/hiwFdUOZZEEeSTm8s0I=,tag:pmiwJSl33ZaNhkaDUTKoRQ==,type:str]
discord-client-id: ENC[AES256_GCM,data:LQaBs05MrzzPOoqrBBpRw8ww9w==,iv:oloZQ4LhV+yQ0DgIwQRWfVBlzf0CVRMpmfjVRttLR/A=,tag:sVkaN3e/VxEJsWecR7bzUA==,type:str]
discord-client-secret: ENC[AES256_GCM,data:Yj1iURiMC5KhxKlw/7n5ZzgU2TNh8322JL7XJCTa2uU=,iv:cgT8GPWGBZUW0PLehWIhljLQFBx7MNihQSP+NRCuduo=,tag:oKbKmkhBLLftnJqU5H3PkQ==,type:str]
discord-bot-token-id: ENC[AES256_GCM,data:p/Befm7gDqv6nJRUlTynEh4xPnnhav555Ki2TOa9oXJiw+twzFwAbERjGSxm64NeJeDKrfu/IGdsY9rezUZKiVCsDSO7ALDJ,iv:F7/B6zHvoqs5EHZJP/5AprYbxmU5wYG5oxY1Qw/A3Z8=,tag:XKKO7j7BfW7dnkAPh2amuw==,type:str]
github-client-id: ""
github-client-secret: ""
telegram-bot-token: ""
telegram-bot-name: ""
threads-client-id: ""
threads-client-secret: ""
facebook-app-id: ""
facebook-app-secret: ""
linkedin-client-id: ENC[AES256_GCM,data:x6GA/vEGwEugh1uyHiM=,iv:429d7+JmOEnEoU5UxrZWAc0zeEjpSqVaTGqyXnRaMCE=,tag:v43uW3laOhfhsBvatfPhug==,type:str]
linkedin-client-secret: ENC[AES256_GCM,data:xTO+P5yPW86m9HbzJwZBtW6HwijyONYuVr5kU9/vQKTZ,iv:jsD298dx5XMziKm/t9N7NgXE+x+KK4n3BilfjSRcmDA=,tag:O2dvGJkxuaD+KS/ZaSr5iw==,type:str]
pinterest-client-id: ""
pinterest-client-secret: ""
reddit-client-id: ENC[AES256_GCM,data:/vKmIMCm8pwkwU1I1a5xCaPoxVI4ew==,iv:MuAjWIWmf0YUZauGSUYHNJo35NBpCyfdsw9CyDzQBzo=,tag:Z7uyB250+eUxpJ7iut9zjQ==,type:str]
reddit-client-secret: ENC[AES256_GCM,data:R7mn36rC1Q2m6OmJZv/rA3kmvKyXgT6QYnQdPflU,iv:sCHtH6bo1TjLgqICj43wrJRH/WzpReVbnatVd3tj7t8=,tag:szxF3ofzTV9jpUYHcSngcg==,type:str]
slack-id: ENC[AES256_GCM,data:PSJEAtcviDkes8cDXyrt2liKf5EVIY5cM8QT,iv:j+p5VXCTWLN7Af4Ffi03jM4yvNxMPnGykjgUh2R1QLs=,tag:QnQuSGzdXDsqhmt699xZ3g==,type:str]
slack-secret: ENC[AES256_GCM,data:8QcWtBX1Bp6WK21/3mINNf2ZWkEATGUFmZhUbfkkw20=,iv:F+HPXo3hyHXkh6tD9vXLICHlA6g6w6AyD6hTioGslDs=,tag:r6Z4ES417jPcWYTVslnekA==,type:str]
slack-signing-secret: ENC[AES256_GCM,data:PuetBCBo5aKFn3bJYGgQuZyDSJeETfu+1wsgMMQBOr8=,iv:APkbXbuUaGuTgkZMAvko1PisJE8+hvhtyfKC0hrzn7A=,tag:1mijZ0yXupza50OkAxofnA==,type:str]
x-api-key: ENC[AES256_GCM,data:xF5pZRYYk3zeViT2LC6IXSanTJP6E6dIsXAbhzyRil0ZsA==,iv:/J0M3W1CoQ4ct7sUAY1JQg7br0s63fNkl7+/z6Kuc88=,tag:bqX4ivNUjdpPaMdTOfsdaQ==,type:str]
x-api-secret: ENC[AES256_GCM,data:TFA9cF6A9bpFZP9GX7EU+W7+DcvSLrITfmNTpda0m1tXKrWL1ybIXSYYOa9uH8aqpY4=,iv:KcVTgnQqHn5ENPiY0VhbP8vdJZxR3oRpACk1urJMXbw=,tag:onLcOuuAGx9BegqZBO/OlA==,type:str]
youtube-client-id: ENC[AES256_GCM,data:GiRCANjyQLuFvqNO+yrR1aVG7gqpN7XQRAyrJTjBlgFakFCaDy4azQAGPvT+8x2FGHswcfH0fZJrZOW0MJaAw0NBZAihb8Yn,iv:U45TxfnBVGDtJUdFudqB/8Yq3GBGBmh7jqYBGB5g6kM=,tag:Xuk0quE/wxNo7p6Hm7Ai7Q==,type:str]
youtube-client-secret: ENC[AES256_GCM,data:0/o3qNGbbkFaFttV0zPerUZKsKnowNiHMPC4hyamLbrAYIg=,iv:sm3DTV0JMKfTPNlT6GxXnIS8GKBc0IO8GJF0prutXGs=,tag:RIMcNvT6r9NRJo1Rm7HyGQ==,type:str]
openai-api-key: ENC[AES256_GCM,data:AUa6hPfhWHkgXkSVy52VcKFru/rQxOb2ZiAK+O4WWEZ1JcFMALNLQGZhtTJNRa3VAOKJkZxb2eiLb1QBHDiAf0amkyLtg5VjdA6JEIWTcKRqArr5lQ87p5kJyQcXyOcRWs8b+cRax9kONKuNeeUhPadS4VFXIeuiCKmqtudOPRp1nvl6NQqQga0OnPq31Z7x4tBNwh/3bnq9sHFfOGDv3Hm07jU=,iv:+hNJtsN5I8Yr5FUmXfWbeOvb7Lh0oL5DUvxUObOnbIM=,tag:Ho/ka3nPL9vAXJiiQ0ZCcw==,type:str]
sops:
    age:
        - recipient: age1ypmym3g6ql22en2r22czt4r98c6pqljtppv64qk0kdez2ydf5uxqqytgzs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YWZKOTNTRzU2QXYyUnFp
            cmlRaE1ZeDFwZ1NVMTdabnJCOTJ6V0xyQUZNClZCYk9RRVk3a3BGTHh2dnpRVjZq
            VFk1aHVXb2ExeFR4aU9XdFBoTjUwSnMKLS0tIDBIa1MrV1hSOWdCS09peWVuWjhi
            ODJWZXMwelFYS1U2NXFXc2x3VGhjV0EK4IKKTP933i1Euj7NIvSES/u9CkG3pXNW
            ZMJEHu1dF3SiHjV0q2wyl4Znp0y31Sa8ozoqdUHmbMcC9CTWvbqCNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T10:22:05Z"
    mac: ENC[AES256_GCM,data:PfgcFeI7L4EllHdUlNTX2Z0D/hAG9m+qVe4WrEh5M7c3mj/qnr5JvpssI6GQZUBOamvi39nJUQjG7GcvJD2awMxS5Pad4lFA1/0jHAaPVCatpbzN18HdKn0Hm7bG0jyyZSdFfGHVZXRgXBzFi8Y1oULviX2w9auw8r7H/aNSUek=,iv:KjD5vAMo/thXXmiQtMd7svwplGhNutFbJDcGWo8+Hak=,tag:6jb/4kyDXxFL2JIKxa8xOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
