namespace: ENC[AES256_GCM,data:w/AI+9hEVyjH5PTwPoAA2gos,iv:6LglB4XGcOcOLFboW/X5+kR6JuFajwkc30dMX4lpt5w=,tag:w8dpxYUImwzAL/sW8Y84+w==,type:str]
db-name: ENC[AES256_GCM,data:hXQj/tVs,iv:WDdERAa03WGlHpkYfx7MWGnzhg06o5M8tnoIi30Oevg=,tag:8fBAxbNMPJtd8QWPx24d4w==,type:str]
db-user: ENC[AES256_GCM,data:dgFdG5SG,iv:fdYv2Lkqs1g8EVstH1N59+XtGRUvC4279HYm5RqPd5k=,tag:HiWK8Kroj6imWXnUhgMBzg==,type:str]
db-password: ENC[AES256_GCM,data:JHICSRQAvJ1/rg8oyNlz,iv:dUPDdA3F73YdWS5z6rR2CQvuM5tkSW9zKB2HLW/V6+s=,tag:1cchbL1W8w9WIOcfPYujYg==,type:str]
db-url: ENC[AES256_GCM,data:O6uhStTplesM54EMdHjOuDXKsz8gx/yc8Su74I5cTz4jH4n9jz2Su1V2UJ2/uwYZ4HXyjhM0EjGGSHpRh9vT4IFTCmtRg+QIR44xqXescn8u/RP5jtbqjWLa479YyB8=,iv:c0JrbOzav/Jt6cy/x0D53Jxh9flaxWtTZ7P7Hn4r0+A=,tag:aoMiY/SmhLlckDOgHy4ySg==,type:str]
redis-password: ENC[AES256_GCM,data:h9R1iVneajHsIVePFzw1X8Pj7IDj,iv:h8PRS0ukFp0mkWw6Z1eKFWwSY75XY3eoH15mx+vkoI0=,tag:4ByFStN7AaPEguuWgii+pg==,type:str]
jwt-secret: ENC[AES256_GCM,data:cobuuhwbQLNGXkxnCcRLXhhdmuzmEskBjgdAvfJP1ckOYZ5jIknZm/oj1j0Q33X2yNsRmmaMY0yuHpYw0F30HAczRnWmW1B/LQd6Tg==,iv:Zsd8QdUWY/zM46ElM/Mrq49pw9FRyy384YwNEsnSQcY=,tag:4z8TFn6mk3sXDFYR9Wjg/w==,type:str]
email-from-address: ENC[AES256_GCM,data:SbhjPQa+F6vpW5eTaMRNKdb0,iv:d4YB759cjZ+ucS3+UnXh/XMZkpH52BY1coxfFvPehJQ=,tag:48dYWB1efnRgGwtr7KCz5w==,type:str]
email-from-name: ENC[AES256_GCM,data:Ab73nS30mg==,iv:uV4asmydZg4nCOKctIlWfwxqU8Lz/cZfG/z8E+4vO3s=,tag:8EaVmVg5/tlR4cZut/tYGw==,type:str]
cloudflare-account-id: ENC[AES256_GCM,data:SrDkStfZf9XzfkCmEHn2WGXXtHmZImwgjCe1Tma6zJ8=,iv:4XN6HKqQRW+I7homfGUqyJL7+ownicWblM891+nx+ug=,tag:A0q1n63ErOQlMDq1iJFdVQ==,type:str]
cloudflare-access-key: ENC[AES256_GCM,data:k4RQGKfsyDP1vRGFCKFP4Ch/AOig4Izx/GeNcim+b/I=,iv:4x/BnOj/tflwlntd/DbYu2F6I34o5P7TfbANPz1X8Ok=,tag:/9OqH4v3mlw3/RPhdZa6SQ==,type:str]
cloudflare-secret-access-key: ENC[AES256_GCM,data:vUjvBpr7oGCiXuYnlh/fd7bzlP/+YeNiCDF+QfLOfr6rlipSZMFOIG7mZttHLHaOLqDM/MXhCajNQuD33zp1Fw==,iv:EbTm8lVWNylMWAsOj4wY7A03MlwMQDZBeyzbdwF7nt4=,tag:gM4XrqUz1jsVfswd63OzKA==,type:str]
cloudflare-bucketname: ENC[AES256_GCM,data:4caKHyLM,iv:xYNWtUXiOwdPcJYP7xLDFmLcXiN4UKPFYcFE4AFSLfY=,tag:zqj7YAyw4D3mMk3azbtytQ==,type:str]
cloudflare-bucket-url: ENC[AES256_GCM,data:lTmBjaNS3kHX3xFS6lDYdh1udplsvpQrZ0/xzt/QTPcOsio1GoZkPhcdZq4vNaaJRvQSw3z6vUBUsmk61c5Ks08=,iv:tw+k1x9SizKS7emjXdIAkce9u2OonCV1rWI3fbteoJY=,tag:9fK5tzvVUDdcYTG+0AX3qA==,type:str]
cloudflare-region: ENC[AES256_GCM,data:6pRQdg==,iv:WI/KG6WCr2JKEVsbo8juKkFT5MDO38J9dSBylpzYhf0=,tag:Nn9EDnoJRVKIZOUSVwH7kA==,type:str]
discord-client-id: ENC[AES256_GCM,data:rdeH/m9kzn6aSRG/oCRElAFq3g==,iv:f3dbxXTjFae7cFU1fwM7ubQ52Rl3oWXOEgLH+yNODyc=,tag:KdMq5l9DGRxtH9gR2n4KWw==,type:str]
discord-client-secret: ENC[AES256_GCM,data:rcdUSiYTKIM8vH3bvocdpnedAiBNNuUTSldg8eGV8Qc=,iv:ZV1hEUpCStZjmEZrnnyqPrhINylWMv2IpObdEXdeO5U=,tag:La/ZVdy8bHqUutq3fgmMgQ==,type:str]
discord-bot-token-id: ENC[AES256_GCM,data:xuui6lhCfKjp7j2AzrjM6YiL+futJRWsWUS2dC7jQOcjR9/ck2fLsD8V06Z0QumVd4oksFsNI6UK/Opgz8NNyAnySSmzb8oM,iv:6nddUpoVyot3wlxNe2e/c5wsoNq9JuugzsBplXFpTqk=,tag:Y7r2aGquhkDsPTUEvRd0+w==,type:str]
github-client-id: ""
github-client-secret: ""
telegram-bot-token: ""
telegram-bot-name: ""
threads-client-id: ""
threads-client-secret: ""
facebook-app-id: ""
facebook-app-secret: ""
linkedin-client-id: ENC[AES256_GCM,data:g9gHG1+21rGSqjhqSRI=,iv:XB7JWo61UIHz/SMz2YTlEllN0IVdCaBLs8fASpmiRq4=,tag:oAb7TJjnpMcqpL5ocDWWAw==,type:str]
linkedin-client-secret: ENC[AES256_GCM,data:WIf5GY/Nq8k1CAts89TD1dtxqP5Tz2CbkdPUYthmgOaL,iv:MonuQG74CATnpLPR1goRdeSOUuHIRNy7vhAqGm3YBc4=,tag:q+Vjoe9Ln5mM5od8p1EE3A==,type:str]
pinterest-client-id: ""
pinterest-client-secret: ""
reddit-client-id: ENC[AES256_GCM,data:s6RQ7benhre+UwwqK9yCPtZ+QRIDOQ==,iv:F28dLMSXHO9Jn1wAB4F2HiK4GoB2fN4Y8f5fYKZ1M4M=,tag:bvJAMsHeytxMXf/iAMXwFQ==,type:str]
reddit-client-secret: ENC[AES256_GCM,data:snvGMjf/gAd4P/gltTRWLlimQeYShewZVlLPkVsQ,iv:8wac3Vfqx+Mujn4+VhlYh5KliR+qhzKshclSaVWno4U=,tag:XeQPzyl6Df8jf9v0xWm0AA==,type:str]
slack-id: ENC[AES256_GCM,data:nTQIM3BLMYnrx2TjRF+lXcvcQLDcmz1TECx3,iv:+bvPFQlUSDjZLhKSJUs3iivjiqpEfBz9o9PpR/36gII=,tag:+eTBk8y2DB37XOTjCNRZWQ==,type:str]
slack-secret: ENC[AES256_GCM,data:jG98kXr1oJGi9FhiB6LI+F0aV9s6hXkDBmzZ/BgYmCg=,iv:baEFWQtslWHQ+IFtKGETteYCq4xjKOuWsbT0E5/Oa78=,tag:/313dQPBFVu1ifIr7PDrNQ==,type:str]
slack-signing-secret: ENC[AES256_GCM,data:HaKkAr/D/q5DsOZjrrF10HPly5s90zXXTjJlgkUxvXg=,iv:eIUjdin7/t3GqvCNaV0O8WC/kgqEinNw1DL/ssN1D+E=,tag:sjTrtyBT6t4GZtJjEf5wpA==,type:str]
x-api-key: ENC[AES256_GCM,data:kHCtTyLtlnzenErTQAxg3Q27S9W3hBIIpPqoA365ErQI9g==,iv:9XGafxQSqlEPzDMzXrYfbuu7SrF1bfXnYX1AL3ReX3s=,tag:zsHX2SJU7Jokd9Js9rl3vQ==,type:str]
x-api-secret: ENC[AES256_GCM,data:YOw+md5sXlVdd+gy3LyKp+PqqGSQjfIy5z9czTxYnsv6Ofe8B2HSIHtj5lOfZHbPeS0=,iv:Es8SgF1+NSwh3ltE/kpJbyJlXv7vQOcECmUI4RmEUxA=,tag:NJchLw+8QUht1cJakwdyZQ==,type:str]
youtube-client-id: ENC[AES256_GCM,data:d3r1q45dbbJ1yhkQc0TVGoK2Ot7PD4r8MxKTqAt2oJa6etcEKIrtoPMyn9De0gLIzbEwSEp8bcXeKSYP/wKGRmhBOMSjkghw,iv:jYy2QKjFVylmXSLlttJX8wQLILqxV+RYbzmp1VIGjvs=,tag:lzIoq3quT2A7vuWQrSRXNQ==,type:str]
youtube-client-secret: ENC[AES256_GCM,data:zgDWlyhU2Z5MnWk9RCMiLNqVkIgporwu3bBoKQ2Hnzdt1Jo=,iv:wVTtp4gwsyqg5f/d52+6kIFUrwpiFnOT6ufIxB9gBPA=,tag:XxPIhOIazqS0famEkF9htg==,type:str]
openai-api-key: ENC[AES256_GCM,data:O9S4AxagrhiBeUQSczIAE661ys4GyFmyrwizoMF/GkiDLJCIVFd33NSSytqNekOW0ROxTLY2pzyEtd1IjnD1tQoJDPPpPmoBV25tPrXe6nKgNw1LhGE/Fo7lYYu/Fmyi6Whkb4MfBEWIijoiPf8C8Tjo3j0L2XWpu5Nt7acTOQK9/uY1u5Ujbie7rR2IgJeth2slDlHKbpVaXmoXFhaERdBqKEY=,iv:LfoRS5d0ADuXl5WO8gkxiotPPo3gpXPUuLSVDYILtFk=,tag:1sTnVYWBPr3Jf1fQ8wt3mA==,type:str]
sops:
    age:
        - recipient: age1ypmym3g6ql22en2r22czt4r98c6pqljtppv64qk0kdez2ydf5uxqqytgzs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUExYKy90Z01qUnZ5ek8y
            SjJPU1JqQTNENWdsNkRtN0svVk8zbGNzaVZJCkxIeE1RemlyWDArcW9WYWNmc3JN
            ZkJWNEUrNzlDN0pEWHkxcktCQmZvOUkKLS0tIHp3ZzVsQ0dGMGVVUk9FQW9RNEsy
            Z2ZsSlpmSnFkT1JYaDRoVE5JM0xpa2cKLeSdh2zJhoJjurAYRib1Nfp7e3Ymohls
            gz6fZpsodznG//MhLQGFRyqQuTW3IEOjzO5vHnInhRIz679xbZKZ+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T10:36:03Z"
    mac: ENC[AES256_GCM,data:md+yp5l5dpLH3GYNPMTO4sLfUabzgiP3kyoeq2e5lr7Gw3k7mhxPyoVk19ccrVMvEt33xvH5oYM8IjTP8npyHH47IS2I0JHtFJChu1agauPFMFKlvrFaQvDi3mS9SMuT3E5TkSmIKDeBySY0lW8SIoEOXXx39OtvrWjthJ6Az/c=,iv:HJMJHzkI4pnMULD4BnQg3zKYpH0JeRQSvrfemDthpT4=,tag:IPshpLte/xJ0stN464I0vQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
