apiVersion: v2
name: postiz-application
description: "Helm Chart for deploying postiz-application on Kubernetes"
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: app-template
    repository: oci://ghcr.io/bjw-s/helm
    version: 3.6.0
    alias: application
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.7.27
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 22.0.7
    condition: redis.enabled
