# Example values for Postiz Helm Chart
# Copy this file to values.yaml and customize for your environment

postiz-app:
  # Number of application replicas
  replicaCount: 1

  # Container image configuration
  image:
    repository: ghcr.io/gitroomhq/postiz-app
    pullPolicy: IfNotPresent
    tag: "latest"

  # Kubernetes service configuration
  service:
    type: ClusterIP
    port: 80

  # Ingress configuration for external access
  ingress:
    enabled: true
    className: "nginx"  # Update based on your ingress controller
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Update based on your cert-manager setup
    hosts:
      - host: postiz.yourdomain.com  # REQUIRED: Replace with your domain
        paths:
          - path: /
            pathType: Prefix
            port: 80
    tls:
      - secretName: postiz-tls
        hosts:
          - postiz.yourdomain.com  # REQUIRED: Replace with your domain

  # PostgreSQL database configuration
  postgresql:
    enabled: true
    auth:
      username: postiz
      password: "CHANGE-ME-SECURE-PASSWORD"  # REQUIRED: Generate a secure password
      database: postiz
    primary:
      persistence:
        enabled: true
        size: 20Gi
        storageClass: "gp2"  # REQUIRED: Update with your storage class

  # Redis cache configuration
  redis:
    enabled: true
    auth:
      password: "CHANGE-ME-REDIS-PASSWORD"  # REQUIRED: Generate a secure password
    master:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: "gp2"  # REQUIRED: Update with your storage class

  # Application environment variables
  env:
    FRONTEND_URL: "https://postiz.yourdomain.com"  # REQUIRED: Update with your domain
    NEXT_PUBLIC_BACKEND_URL: "https://postiz.yourdomain.com/api"  # REQUIRED: Update with your domain
    BACKEND_INTERNAL_URL: "http://backend:3000"
    IS_GENERAL: "true"
    DISABLE_REGISTRATION: "false"  # Set to "true" to disable user registration

  # Sensitive environment variables (stored in Kubernetes Secrets)
  secrets:
    # Database connection string (update based on your PostgreSQL config)
    DATABASE_URL: "postgresql://postiz:CHANGE-ME-SECURE-PASSWORD@postiz-postgresql:5432/postiz"
    
    # Redis connection string (update based on your Redis config)
    REDIS_URL: "redis://:CHANGE-ME-REDIS-PASSWORD@postiz-redis-master:6379"
    
    # JWT secret for authentication (REQUIRED: Generate a secure random string)
    JWT_SECRET: "CHANGE-ME-JWT-SECRET"  # Generate with: openssl rand -base64 32
    
    # Social media API keys (optional but recommended for full functionality)
    X_API_KEY: ""
    X_API_SECRET: ""
    LINKEDIN_CLIENT_ID: ""
    LINKEDIN_CLIENT_SECRET: ""
    REDDIT_CLIENT_ID: ""
    REDDIT_CLIENT_SECRET: ""
    GITHUB_CLIENT_ID: ""
    GITHUB_CLIENT_SECRET: ""
    
    # Email notification configuration (optional)
    RESEND_API_KEY: ""
    
    # Cloud storage configuration (optional - for media uploads)
    CLOUDFLARE_ACCOUNT_ID: ""
    CLOUDFLARE_ACCESS_KEY: ""
    CLOUDFLARE_SECRET_ACCESS_KEY: ""
    CLOUDFLARE_BUCKETNAME: ""
    CLOUDFLARE_BUCKET_URL: ""

  # Resource limits and requests
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  # Horizontal Pod Autoscaler configuration
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

  # Advanced scheduling configuration
  nodeSelector: {}
  tolerations: []
  affinity: {}