namespace: postiz-application

_shared_config:
  hostname: &hostname postiz-application.staging.k8s.webgrip.nl
  url: &url https://postiz-application.staging.k8s.webgrip.nl

postiz-app:
  replicaCount: 1

  image:
    repository: docker.io/webgrip/postiz-application
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 80

  postgresql:
    enabled: true
    auth:
      # The postgresql subchart expects plain string values here.
      # Use build-time or CI-injected values (or leave defaults) instead of object mappings.
      username: postiz
      password: postiz-password
      database: postiz

  redis:
    enabled: true
    auth:
      # Redis password must be a string for the redis/postgres subcharts.
      password: postiz-redis-password

  ingress:
    enabled: true
    className: ingress-traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-traefik
    hosts:
      - host: *hostname
        paths:
          - path: /
            pathType: Prefix
            port: 80
    tls:
      - secretName: postiz-tls
        hosts:
          - *hostname

  # Application environment variables
  env:
    FRONTEND_URL: "https://postiz-application.staging.k8s.webgrip.nl"
    NEXT_PUBLIC_BACKEND_URL: "https://postiz-application.staging.k8s.webgrip.nl/api"
    BACKEND_INTERNAL_URL: "http://backend:3000"
    IS_GENERAL: "true"
    DISABLE_REGISTRATION: "false"

    # Database / Redis
    DATABASE_URL:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: db-url
    DB_NAME:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: db-name
    DB_USER:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: db-user
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: db-password
    REDIS_URL:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: redis-password
    DB_HOST: "postiz-application.postgres"
    DB_PORT: "5432"
    REDIS_HOST: "postiz-application.redis"
    REDIS_PORT: "6379"

    # Auth / tokens
    JWT_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: jwt-secret

    # Email
    EMAIL_FROM_ADDRESS:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: email-from-address
    EMAIL_FROM_NAME:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: email-from-name

    # API keys and platform clients
    X_API_KEY:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: x-api-key
    X_API_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: x-api-secret
    OPENAI_API_KEY:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: openai-api-key
    RESEND_API_KEY:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: resend-api-key
    STORAGE_PROVIDER: "cloudflare"

    # Social / OAuth clients
    LINKEDIN_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: linkedin-client-id
    LINKEDIN_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: linkedin-client-secret
    GITHUB_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: github-client-id
    GITHUB_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: github-client-secret
    REDDIT_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: reddit-client-id
    REDDIT_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: reddit-client-secret
    DISCORD_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: discord-client-id
    DISCORD_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: discord-client-secret
    DISCORD_BOT_TOKEN_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: discord-bot-token-id
    TELEGRAM_BOT_TOKEN:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: telegram-bot-token
    TELEGRAM_BOT_NAME:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: telegram-bot-name
    THREADS_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: threads-client-id
    THREADS_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: threads-client-secret
    FACEBOOK_APP_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: facebook-app-id
    FACEBOOK_APP_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: facebook-app-secret
    PINTEREST_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: pinterest-client-id
    PINTEREST_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: pinterest-client-secret

    # Misc and developer flags from .env
    MASTODON_URL: "https://mastodon.social"
    NEXT_PUBLIC_DISCORD_SUPPORT: ""
    NEXT_PUBLIC_POLOTNO: ""
    NOT_SECURED: "true"
    API_LIMIT: "30"
    FEE_AMOUNT: "0.05"
    STRIPE_PUBLISHABLE_KEY: ""
    STRIPE_SECRET_KEY:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: stripe-secret-key
    STRIPE_SIGNING_KEY:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: stripe-signing-key
    STRIPE_SIGNING_KEY_CONNECT:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: stripe-signing-key-connect
    NX_ADD_PLUGINS: "false"

    # Slack
    SLACK_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: slack-id
    SLACK_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: slack-secret
    SLACK_SIGNING_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: slack-signing-secret

    # YouTube
    YOUTUBE_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: youtube-client-id
    YOUTUBE_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: youtube-client-secret

    # Cloudflare
    CLOUDFLARE_ACCOUNT_ID:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: cloudflare-account-id
    CLOUDFLARE_ACCESS_KEY:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: cloudflare-access-key
    CLOUDFLARE_SECRET_ACCESS_KEY:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: cloudflare-secret-access-key
    CLOUDFLARE_BUCKETNAME:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: cloudflare-bucketname
    CLOUDFLARE_BUCKET_URL:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: cloudflare-bucket-url
    CLOUDFLARE_REGION:
      valueFrom:
        secretKeyRef:
          name: postiz-application-secret
          key: cloudflare-region

  # Resource limits and requests
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
