namespace: postiz-application

_shared_config:
  hostname: &hostname postiz-application.staging.k8s.webgrip.nl
  url: &url https://postiz-application.staging.k8s.webgrip.nl

application:
  enabled: true

  controllers:
    main:
      pod:
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          fsGroup: 1500
          fsGroupChangePolicy: OnRootMismatch

      containers:
        main:
          image:
            repository: docker.io/webgrip/postiz-application
            tag: "latest"
            pullPolicy: Always
          securityContext:
            runAsUser: 1500
            runAsGroup: 1500
            allowPrivilegeEscalation: false
          env:
            - name: FRONTEND_URL
              value: "https://postiz-application.staging.k8s.webgrip.nl"
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "https://postiz-application.staging.k8s.webgrip.nl/api"
            - name: BACKEND_INTERNAL_URL
              value: "http://backend:3000"
            - name: IS_GENERAL
              value: "true"
            - name: DISABLE_REGISTRATION
              value: "false"
            - name: NEXT_PUBLIC_DISCORD_SUPPORT
              value: ""
            - name: NEXT_PUBLIC_POLOTNO
              value: ""
            - name: NOT_SECURED
              value: "true"

            # Database
            - name: DB_HOST
              value: "postiz-application.postgres"
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: db-url
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: db-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: db-password

            # Redis
            - name: REDIS_HOST
              value: "postiz-application.redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: redis-password

            # Auth / tokens
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: jwt-secret

            # Email
            - name: EMAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: email-from-address
            - name: EMAIL_FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: email-from-name

            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: resend-api-key

            # Social logins
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: x-api-key
            - name: X_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: x-api-secret
            - name: LINKEDIN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: linkedin-client-id
            - name: LINKEDIN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: linkedin-client-secret
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: github-client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: github-client-secret
            - name: REDDIT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: reddit-client-id
            - name: REDDIT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: reddit-client-secret
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: discord-client-id
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: discord-client-secret
            - name: DISCORD_BOT_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: discord-bot-token-id
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: telegram-bot-token
            - name: TELEGRAM_BOT_NAME
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: telegram-bot-name
            - name: THREADS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: threads-client-id
            - name: THREADS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: threads-client-secret
            - name: FACEBOOK_APP_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: facebook-app-id
            - name: FACEBOOK_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: facebook-app-secret
            - name: PINTEREST_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: pinterest-client-id
            - name: PINTEREST_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: pinterest-client-secret
            - name: SLACK_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: slack-id
            - name: SLACK_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: slack-secret
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: slack-signing-secret
            - name: YOUTUBE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: youtube-client-id
            - name: YOUTUBE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: youtube-client-secret

            # Cloudflare
            - name: CLOUDFLARE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: cloudflare-account-id
            - name: CLOUDFLARE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: cloudflare-access-key
            - name: CLOUDFLARE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: cloudflare-secret-access-key
            - name: CLOUDFLARE_BUCKETNAME
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: cloudflare-bucketname
            - name: CLOUDFLARE_BUCKET_URL
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: cloudflare-bucket-url
            - name: CLOUDFLARE_REGION
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: cloudflare-region
            - name: STORAGE_PROVIDER
              value: "cloudflare"

            # Stripe
            - name: FEE_AMOUNT
              value: "0.05"
            - name: STRIPE_PUBLISHABLE_KEY
              value: ""
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: stripe-secret-key
            - name: STRIPE_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: stripe-signing-key
            - name: STRIPE_SIGNING_KEY_CONNECT
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: stripe-signing-key-connect
            - name: NX_ADD_PLUGINS
              value: "false"

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: postiz-application-secrets-2
                  key: openai-api-key
            - name: API_LIMIT
              value: "30"

    service:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4200
        api:
          port: 3000
          targetPort: 3000

  ingress:
    main:
      enabled: true
      className: ingress-traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-traefik
        traefik.ingress.kubernetes.io/router.middlewares: ingress-traefik-ryan-home-ip-allow-list@kubernetescrd
      hosts:
        - host: *hostname
          paths:
            - path: /
              service:
                identifier: main
                port: http
            - path: /api
              service:
                identifier: main
                port: api
      tls:
        - secretName: letsencrypt-postiz-application
          hosts:
            - *hostname

postgresql:
  enabled: true
  image:
    repository: bitnamilegacy/postgresql
    tag: "17.6.0"
    pullPolicy: IfNotPresent
  architecture: standalone
  auth:
    username: postiz
    database: postiz
    existingSecret: postiz-application-secrets-2
    existingSecretPasswordKey: db-password
  primary:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: do-block-storage
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"

redis:
  enabled: true
  image:
    repository: bitnamilegacy/redis
    tag: "8.2.1"
    pullPolicy: IfNotPresent
  architecture: standalone
  auth:
    enabled: true
    existingSecret: postiz-application-secrets-2
    existingSecretPasswordKey: redis-password
  master:
    persistence:
      enabled: true
      size: 1Gi
    disableCommands: [FLUSHALL, CONFIG, KEYS]
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "150m"
      memory: "256Mi"
