apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mariadb-password: {{ index .Values "db-password" | b64enc | quote }}
  mariadb-root-password: {{ index .Values "db-root-password" | b64enc | quote }}

  app-key: {{ index .Values "app-key" | b64enc | quote }}
  api-secret: {{ index .Values "api-secret" | b64enc | quote }}
  user-password: {{ index .Values "user-password" | b64enc | quote }}
